apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: adverse-sparrow-python 
  janus-idp.io/tekton: adverse-sparrow-python
  backstage.io/kubernetes-id: adverse-sparrow-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: adverse-sparrow-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  