apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: adverse-sparrow-python
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:b8a4fd05a6afe55c32170156049e60b464a1fbb8@sha256:61ce867688f0fd8b9b029daf5d0d9ed0b0d4600f7fed4eb0ea8753d5ac83487c
        name: container-image  
